### ISSUE TITLE
adding new wrapper to docs

### ISSUE THREAD

**Issue by dshomoye** [afuh/rick-and-morty-api#101]
I created a [rust wrapper ](https://crates.io/crates/rick-and-morty) for the api -- should I create a PR directly to add this?

**Comment by afuh** [comment]
Hey @dshomoye 
that's great!! thank you so much for contribution! 

Please open a PR in the [docs](https://github.com/afuh/rick-and-morty-api-site/blob/develop/src/pages/documentation.mdx#libraries).  and please also update the [tests](https://github.com/afuh/rick-and-morty-api-site/blob/develop/cypress/integration/documentation.js#L3)

**Comment by dshomoye** [comment]
Done: https://github.com/afuh/rick-and-morty-api-site/pull/63
