### ISSUE TITLE
GraphQL: Characters nullable filter fields fails when null is passed

### ISSUE THREAD

**Issue by emileber** [afuh/rick-and-morty-api#103]
```graphql
query {
  characters(filter: { name: null }) {
    results {
      name
    }
  }
}
```

```json
{
  "errors": [
    {
      "message": "404: Not Found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "characters"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "http://localhost:8080/api/character/?name=null&page=undefined",
          "status": 404,
          "statusText": "Not Found",
          "body": {
            "error": "There is nothing here"
          }
        }
      }
    }
  ],
  "data": {
    "characters": null
  }
}
```

---

## Expected behaviour

The filter field being ignored.

## Current behaviour

The `null` filter field value is being converted to a string and it's being sent to the REST API.

```
http://localhost:8080/api/character/?name=null&page=undefined
```

Note that the same thing happens with the `page` parameter, but it doesn't fail in this case.

**Comment by emileber** [comment]
A possible solution would be to filter `null` and `undefined` values from filters before passing them to the `get` params in the source.

```javascript
const pruneObject = (obj) => Object.fromEntries(
  Object.entries(obj).filter(([_, v = null]) => v !== null)
);
```

```javascript
  characters({ filter, page }) {
    return this.get('/', pruneObject({ ...filter, page }));
  }
```

**Comment by emileber** [comment]
Same thing with all filters in fact, like on `locations`

```graphql
query {
  locations(filter: { name: null }) {
    results {
      name
    }
  }
}
```

**Comment by afuh** [comment]
Hey @emileber 
thanks for the detailed report!

I like your solution. What I would do instead of adding it to every `GET` method, would intercept the request with [`willSendRequest`](https://www.apollographql.com/docs/apollo-server/data/data-sources/#intercepting-fetches), what do you think?

**Comment by emileber** [comment]
Yes, makes sense, I don't see a use-case where the literal string `"null"` nor `"undefined"` would be useful, so filtering them out for all _get_ requests would be fine! 👍
