### ISSUE TITLE
Querying for some locations result into an error

### ISSUE THREAD

**Issue by alesmit** [afuh/rick-and-morty-api#104]
I'm getting this error:

```
Cannot read property 'name' of undefined
```

Using the following GraphQL query

```graphql
{
  location(id: 31) {
    residents {
      id
      origin {
        id
      }
    }
  }
}
```

**Comment by ruddenchaux** [comment]
I've a similar error with this GraphQL query
`
query {
  locations(page: 1) {
    results {
      id
      name
      type
      dimension
      residents {
        id
        name
        status
        species
        image
        location {
          name
        }
        episode {
          name
        }
      }
    }
  }
}
`

**Comment by afuh** [comment]
Thank you both for reporting!
