### ISSUE TITLE
Add Postman collection to docs

### ISSUE THREAD

**Issue by loopDelicious** [afuh/rick-and-morty-api#109]
@afuh - do you mind if I create a Postman collection of your API and add it to your GH repo and/or documentation website? I'm happy to submit a pull request if this is welcome.

**Comment by afuh** [comment]
@loopDelicious Thanks for the contribution, it sounds great! 

It would be nice if we can add a link to a repo containing the collections. Happy to add this link to the [readme](https://github.com/afuh/rick-and-morty-api#wrappers) and the [Documentation](https://rickandmortyapi.com/documentation/#libraries). Feel free to open the PRs, or let me know and I can do it.

**Comment by loopDelicious** [comment]
@afuh I added a collection to [my public Postman workspace](https://www.postman.com/joyce-jetson/workspace/joycejetson/documentation/1215211-d616f4dc-8fb9-4726-ab5d-05ce021b4d0e) and [public GitHub repo](https://github.com/loopDelicious/rick-and-morty-postman). If you want to host it, you can take it and link to your version in the readme and docs, or let me know if you want to leave it there.

**Comment by afuh** [comment]
thank you!
