### ISSUE TITLE
Brand-new-well-written-super-cool-blazing-fast Python client implementation

### ISSUE THREAD

**Issue by lucasea777** [afuh/rick-and-morty-api#122]
Dear Axel, I would really like to implement a nice Python client, simple question: 

Would you add it to the official list [https://rickandmortyapi.com/documentation/#python](https://rickandmortyapi.com/documentation/#python)?

It doesnt even have to have my name on it, but I ask just to make sure that it would not be left in the darkness 🙂.

**Comment by afuh** [comment]
Hey @lucasea777 absolutely!! 
Please feel free to open a PR with your the library, we can check it and merge it to the documentation!

**Comment by afuh** [comment]
closing this, feel free to open it again :)
