### ISSUE TITLE
Bad Gateway Response

### ISSUE THREAD

**Issue by LeandroLS** [afuh/rick-and-morty-api#13]
Hello, 

I've observed that sometimes the request from a image returns to me a "502 Bad Gateway". 
Example, I made a request to https://rickandmortyapi.com/api/character/avatar/1.jpeg, the return:
![502badgateway](https://user-images.githubusercontent.com/15800316/38028536-93218216-3269-11e8-8ce8-9436b65efeee.png)
This error occurs randomly, if I do the same request again to the same URL, the image load normally.

**Comment by afuh** [comment]
Should be working now. I was working on one of the servers.
