### ISSUE TITLE
Location Query String Issue

### ISSUE THREAD

**Issue by LeandroLS** [afuh/rick-and-morty-api#19]
Hello,

I'm having issue whit location query string.

This query string don't work:
https://rickandmortyapi.com/api/location/?name=Dimension C-137

But, this query string and others with 'name' parameter and different values works:
https://rickandmortyapi.com/api/location/?name=Citadel of Ricks

**Comment by afuh** [comment]
Hi @LeandroLS 
Thanks for the info. 

The filtering that you are trying to do is working as it should. I mean, you are looking by `?name` when it should be by `?dimension`. 

Try this: 
https://rickandmortyapi.com/api/location/?dimension=Dimension C-137

---
In any case, there was another bug related to your Issue that I am solving at the moment. 

This isn't working now: 
https://rickandmortyapi.com/api/location/?name=Earth (C-137)

So, thank you for that ;)

**Comment by LeandroLS** [comment]
Where I wrote 'https://rickandmortyapi.com/api/location/?name=Dimension C-137' I meant 'https://rickandmortyapi.com/api/location/?name=Earth (C-137)'.

It's working now. Thank you.
