### ISSUE TITLE
error because of requests limit

### ISSUE THREAD

**Issue by irinakarpenko** [afuh/rick-and-morty-api#28]
Hello!

I wanted to use your api in a study project to realize an Android app using some technologies which are new for me, but already reached requests limit and my app doesn't work :(( it seems that I will need to switch to use other api, but I wanted an app devoted to Rick and Morty :(( can we do anything about the limit? Thank you for consideration!

**Comment by afuh** [comment]
Hi @irinakarpenko, 
Thanks for letting me know about the rate limit issue. 

The rate limit is there to make sure that the server can handle a large amount of traffic. You have a couple of options to deal with this: 
- Save the the [data](https://github.com/afuh/rick-and-morty-api/tree/master/data) and use it locally. 
- Save the data as `.json` files and use that in development (you could fetch the entire database with three calls using an array of ids, check [here](https://github.com/afuh/rick-and-morty-api#get-multiple-characters).
- Implement some sort of cache in your project. 

Hope this helps.

**Comment by irinakarpenko** [comment]
Thank you for the answer! I tried to implement cache using okhttp, but today I already won't be able to request the server, so tomorrow I will know whether it works :)
