### ISSUE TITLE
Any plans to add transcripts of each episode to the API ?

### ISSUE THREAD

**Issue by Ic3fr0g** [afuh/rick-and-morty-api#29]
Transcripts would be particularly helpful to create something like a chatbot

**Comment by afuh** [comment]
Hi, 
We honestly never thought about transcripts or how/where to get them, it's a good idea to have in mind. 

Thanks for the suggestion!

**Comment by Ic3fr0g** [comment]
I tried obtaining some transcripts from the Rick and Morty wiki using the link - `http://rickandmorty.wikia.com/wiki/episode-name/Transcript`
Ran some boiler plate code from Beautiful soup to obtain the transcripts from all the pages, however, the transcripts for most episodes are incomplete and inconsistent. But this would be a great resource to start with.

PS. I'm trying to build a chatbot ;)

**Comment by afuh** [comment]
I'm closing this due inactivity.
