### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by christopherkaiser** [afuh/rick-and-morty-api#38]
Get this response when attempting get requests from the api endpoints. Also get this while using rick-and-morty-api-node. I have a sandbox app that uses your api and started getting this error all of a sudden. Thanks.

**Comment by afuh** [comment]
Hey @christopherkaiser 
thanks for letting me know. It should be working now. ;)

This week I am updating and changing all the servers. In addition to that I am slowly adding a new GraphQL endpoint. Maybe there are issues from time to time. I hope to finish by the end of this weekend.

**Comment by afuh** [comment]
Already live! ;)
