### ISSUE TITLE
i think there are no cors headers on 404 response?

### ISSUE THREAD

**Issue by lukasztyszko** [afuh/rick-and-morty-api#42]
hi, I dont really know what im writing but something does not work with 404 responses :)

more info here:
https://stackoverflow.com/questions/54990622/catch-error-message-from-404-response-with-axios-or-fetch-in-javascript

**Comment by afuh** [comment]
Hi @lukasztyszko 

Nice catch! it should be working now. 
Thanks for letting me know about that. 

FYI, [the answer](https://stackoverflow.com/a/54991715) was exactly the issue. 
By default Nginx doesn't add the headers to all responses ([source](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header)).

Thanks!

**Comment by lukasztyszko** [comment]
thanks. 
btw. nice api.
