### ISSUE TITLE
Replace empty string with null

### ISSUE THREAD

**Issue by anthonyBertrant** [afuh/rick-and-morty-api#44]
Hi, great API for me to discover swift Decodable and JSON parsing. But, I just realized that when a field is empty, you return ```""``` instead of a null object.
For exemple, if I get the characters base url ```https://rickandmortyapi.com/api/character/```, the field ```prev``` will have for value ```""``` instead of a more logical ```null``` value.
It's not a very big problem, but when API parsing, have a ```null``` value instand of empty is more convenient.

```json5
{"info":{"count":493,"pages":25,"next":"https://rickandmortyapi.com/api/character/?page=2","prev":""}
```
will be:
```json5
{"info":{"count":493,"pages":25,"next":"https://rickandmortyapi.com/api/character/?page=2","prev":null}
```

Thanks for your work,

**Comment by afuh** [comment]
Hi, 
it makes complete sense.
I will keep this in mind for future updates. 

Thanks for the suggestion.
