### ISSUE TITLE
Expected Iterable, but did not find one for field Character.episode error

### ISSUE THREAD

**Issue by onderonur** [afuh/rick-and-morty-api#45]
Greetings!

I am trying to create a GraphQL client application for this cool API. Nearly everything is going as it should be but when I try to query some of the characters with `episode` field, I got an error. One of the example queries that I tried on the GraphQL Playground is like this;

`query {
  character(id: 8) {
    id
    name
    episode {
      id
      name
      air_date
    }
  }
}`

And it throws this error;
`Expected Iterable, but did not find one for field Character.episode error`

Even though some characters cause this error, some of them don't. For example when the id is 1 or 2 there is no problem.

It is really fun to work with this API and if you can fix this error any time, it would be really cool.

Cheers

**Comment by afuh** [comment]
@onderonur Thank you for letting me know and for writing such a nice detailed issue! ;)  
It should be working now.
