### ISSUE TITLE
i wish i had a episode filter in character api.

### ISSUE THREAD

**Issue by amirziarati** [afuh/rick-and-morty-api#47]
first of all perfect api. really cool.

if i want to get all of a specific episode's characters' details, ill have to either use character urls one by one in episode response (which can be 20 api call and is not wise), or split the episode ids from the end of urls and call Multiple Character api with their IDs (which is an ugly code).

i wish you had a episode filter in character api or you had a list of character IDs instead of list of URLs in episode response.

**Comment by afuh** [comment]
or you can simple use `/graphql`
