### ISSUE TITLE
Adblock blocking request to API

### ISSUE THREAD

**Issue by ShadOoW** [afuh/rick-and-morty-api#49]
Hi Axel,

I was curious to know, if I'm the only one facing this issue.
Chrome Adblock Plus extension is blocking calls to the graphql API.

Usually this can happens if the API URL has the word ```ads``` in it.
Any ideas?

You can test it here: 
https://web-starter-kit-nextjs.herokuapp.com/

Extension:
https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb

**Comment by afuh** [comment]
Hey @ShadOoW 

It's not about the `ads` word, I think it has to do with the trailing slash at the end of the URI:

![Captura de pantalla 2019-08-12 a la(s) 17 38 09](https://user-images.githubusercontent.com/25172241/62877852-38280880-bd28-11e9-96cb-b936103af37e.png)

Try removing it and let me know if that worked.

**Comment by ShadOoW** [comment]
Awesome that solved it, ty for the help!
I will close the issue.
