### ISSUE TITLE
No result from graphql endpoint

### ISSUE THREAD

**Issue by ShadOoW** [afuh/rick-and-morty-api#52]
Hello,

In case you didn't know already, graphql is returning nulls :'(

```{
  "data": {
    "characters": {
      "info": {
        "count": null
      },
      "results": null
    },
    "episode": {
      "id": null
    }
  }
}
```

Feel free to close this issue, I just wanted to let you know about this.

**Comment by afuh** [comment]
Thanks! I will take it a look asap.

**Comment by CeH9** [comment]
Same problem

**Comment by CeH9** [comment]
I guess citizens of backend's microverse started an riot by replacing our models with nulls

![image](https://user-images.githubusercontent.com/7687412/67197087-bc6fc980-f404-11e9-8da6-cd852320d47f.png)

**Comment by afuh** [comment]
I just made a quick fix, it was an issue with the request limit handler. I will take a deeper look at it asap, but now it should work just fine.
Thanks guys for letting me know. I will close this now, feel free to re-open it if you need it.
