### ISSUE TITLE
Cannot access pages

### ISSUE THREAD

**Issue by abhinav-anshul** [afuh/rick-and-morty-api#60]
I tried to access pages from 2-9 but it returns the same Page-1 JSON objects

**Comment by afuh** [comment]
Can you reproduce it? I don't see anything wrong with the pagination 

https://rickandmortyapi.com/api/character/?page=3

**Comment by abhinav-anshul** [comment]
Now I do not see the issue anymore when I tried to get JSON results using postman. Probably it was because I had cached items in my chrome browser.

Hence, I am closing the issue. Thank you
