### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by avenga-oleg-demchuk** [afuh/rick-and-morty-api#72]
Hi:) Thanks for the great API! But now I have a little problem with CORS. I do the API call from the localhost and have this error:

Access to XMLHttpRequest at 'https://rickandmortyapi.com/api/character?page=1' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

Could it be from my side?

**Comment by SyriiAdvent** [comment]
This seems to be a true issue, currently, these endpoints don't work. Giving a CORS rejection error, This pertains to the RESTAPI using GET request. 
`{
  "characters": "https://rickandmortyapi.com/api/character",
  "locations": "https://rickandmortyapi.com/api/location",
  "episodes": "https://rickandmortyapi.com/api/episode"
}`

server.js was updated to require CORS 19 days ago. Could be it.

**Comment by afuh** [comment]
Yes, I am seeing an issue between the cache and CORS. I will look into it. 
Thanks for letting me know.

**Comment by afuh** [comment]
It should work now, thanks!

**Comment by robSamuel** [comment]
Currently I am having the same issue with the CORS. It happens almost always with the following endpoint:
`https://rickandmortyapi.com/api/character?page=1`
