### ISSUE TITLE
Filter characters based on location or origin

### ISSUE THREAD

**Issue by sipandey** [afuh/rick-and-morty-api#79]
Hi Team,

I was going through the graphql schema and found that we can not filter characters based on location or origin currently.

Also, the schema doesn't support sorting currently.

If that can be added to the schema it will be great.

Thanks,
Sid

**Comment by afuh** [comment]
Hi

The GraphQL api supports the same filtering as the REST api. You can check it [here].(https://rickandmortyapi.com/documentation/#filter-characters) 

Thank you for the suggestion. We will keep that in min for future releases.
