### ISSUE TITLE
Is it possible to serve images in webp format?

### ISSUE THREAD

**Issue by ShahAnuj2610** [afuh/rick-and-morty-api#82]
Thanks for this great API. I'm using it in my project here https://github.com/ShahAnuj2610/rick-and-morty-characters (https://rick-and-morty-chars.netlify.app/). Now the images are rendered in `jpeg` format due to which it is rendered slowly. It would be great if the images could be served in `webp` format along with `jpeg` for backward compatibility.

**Comment by afuh** [comment]
Cool project!!! thanks for sharing.

We thought about adding `webp` and we are definitely going to do it at some point in the future. However, at this point we are trying to keep the maintenance costs to a minimum and adding more image sources would increase the bandwidth usage. 

thanks for the suggestion!

**Comment by ShahAnuj2610** [comment]
> We thought about adding `webp` and we are definitely going to do it at some point in the future. However, at this point we are trying to keep the maintenance costs to a minimum and adding more image sources would increase the bandwidth usage.

@afuh No worries!
