### ISSUE TITLE
Character endpoint bad response (REST)

### ISSUE THREAD

**Issue by Alejandro2134** [afuh/rick-and-morty-api#83]
Hi!! When using the character resource from the API (https://rickandmortyapi.com/api/character/) with the page query in the url it gives the wrong data, in this case i give to the query the value 4 but the data from the response is the data from the first page:

![error](https://user-images.githubusercontent.com/32116372/87238810-339f2080-c3cd-11ea-847d-019ef3f77d97.png)

**Comment by afuh** [comment]
Hi @Alejandro2134, 
I don't see this happening here, everything looks fine. 

Could you give more context or a way to reproduce this?

**Comment by Alejandro2134** [comment]
Everything is working fine now, its not a problem of the API, thank you.
