### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by AlexSheva-mason** [afuh/rick-and-morty-api#95]
This character's data appears to have a typo in the name of the character:

`{"id":408,"name":"Quick Mistery Presenter","status":"Alive","species":"Human","type":"","gender":"Male","origin":{"name":"Interdimensional Cable","url":"https://rickandmortyapi.com/api/location/6"},"location":{"name":"Interdimensional Cable","url":"https://rickandmortyapi.com/api/location/6"},"image":"https://rickandmortyapi.com/api/character/avatar/408.jpeg","episode":["https://rickandmortyapi.com/api/episode/8"],"url":"https://rickandmortyapi.com/api/character/408","created":"2018-04-15T20:51:47.778Z"}`

Possibly it was meant to be "Quick Mystery Presenter"?

**Comment by afuh** [comment]
Hey @AlexSheva-mason 
good catch!

fixed: https://rickandmortyapi.com/api/character/408

thank you!
