### ISSUE TITLE
Enhancement for better pagination in Front-end applications

### ISSUE THREAD

**Issue by alikhan866** [afuh/rick-and-morty-api#98]
So now i am sending a `GET` request on `https://rickandmortyapi.com/api/episode/` which gives me the result 

```
{
    "info": {
        "count": 41,
        "pages": 3,
        "next": "https://rickandmortyapi.com/api/episode/?page=2",
        "prev": null
    },
    "results": [.........//20 results here]
}
```

This response is just as the documentation said it would be!, I am implementing pagination and there is a issue

here `response.data.info.next` contains only information about the `next` page 

Lets say i am displaying 20 items per page,

So when i am on Page `1` the `next` property holds only information about items in page `2`

But what if i directly want to jump into items of page `3` ? I would have to call the `API` two times to get the correct response i want

So what i am suggesting is an enhancement of the `response` by adding a new property called `listOfNextPages` or any name of your choosing the response should ideally be something like this : 

```
{
    "info": {
        "count": 41,
        "pages": 3,
        "next": "https://rickandmortyapi.com/api/episode/?page=2",
        "listOfNextPages" : [
          https://rickandmortyapi.com/api/episode/?page=2,
          https://rickandmortyapi.com/api/episode/?page=3
]
        "prev": null
    },
    "results": [.........//20 results here]
}
```

Same should be applied for search `API` aswell

**Comment by afuh** [comment]
Hi @alikhan866

Thanks for the detailed explanation. 
The `next` and `prev` are helper URLs. The pourpouse is to have a quick link to plug in to an event (i.e. the click of a button) 

However you if you want a more detailed pagination implementation in your app, you have to build the UI and the logic with the the data that is provided in the [info](https://rickandmortyapi.com/documentation/#info-and-pagination) section.

**Comment by alikhan866** [comment]
@afuh  If i am in page `1` the `info` section does not contain any `helper URL's` to say jump to page `3` directly . I could simply hardcode the value but that is totally non-scalable . That is why i am suggesting an improvement in the `info` section to contain that data :)

**Comment by afuh** [comment]
> That is why i am suggesting an improvement in the info section to contain that data :)

What I'm trying to say is that you already have that data in the `info` section, from there you can dynamically build the URLs that you need without the necessity of hardcoding anything.

**Comment by alikhan866** [comment]
I dont have that data ... 

`https://rickandmortyapi.com/api/episode/` this gives response 

`  "info": {
        "count": 41,
        "pages": 3,
        "next": "https://rickandmortyapi.com/api/episode/?page=2",
        "prev": null
    },`

Where do i have the data about page `3` ? how do i directly get page `3` details without first calling page `2` ?????

**Comment by afuh** [comment]
Look, I'm trying to help you,  I didn't say that you have the **URLs**, I said that you have the **data** needed to dynamically build them yourself. 

This API provides all you need to build a client side pagination. How you do it, it's completely up to you.

Thanks for the suggestion.

**Comment by alikhan866** [comment]
@afuh  got it thank you for your help
