### ISSUE TITLE
Bad structure of HTTP GET request for episodes

### ISSUE THREAD

**Issue by jdaguilar** [afuh/rick-and-morty-api#99]
In documentation page, I found this issue to get a single episode.

`https://rickandmortyapi.com/api/location/episode/28
`

The API for episodes doesn´t work with `/location`, when it should be:

`https://rickandmortyapi.com/api/episode/28
`

**Comment by afuh** [comment]
@jdaguilar good catch. 
Thanks!

 I'm releasing a fix here: https://github.com/afuh/rick-and-morty-api-site/pull/61
